export const currencies = [
  {
    currency_name: "US Dollar",
    currency_code: "USD",
    symbol: "$",
    country: "us-US",
  },
  {
    currency_name: "Euro",
    currency_code: "EUR",
    symbol: "€",
    country: "eu-EU",
  },
  {
    currency_name: "Japanese Yen",
    currency_code: "JPY",
    symbol: "¥",
    country: "jp-JP",
  },
  {
    currency_name: "British Pound",
    currency_code: "GBP",
    symbol: "£",
    country: "gb-GB",
  },
  {
    currency_name: "Indian Rupee",
    currency_code: "INR",
    symbol: "₹",
    country: "in-IN",
  },
  {
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    symbol: "$",
    country: "au-AU",
  },
  {
    currency_name: "Canadian Dollar",
    currency_code: "CAD",
    symbol: "$",
    country: "ca-CA",
  },
  {
    currency_name: "Swiss Franc",
    currency_code: "CHF",
    symbol: "CHF",
    country: "ch-CH",
  },
  {
    currency_name: "Chinese Yuan",
    currency_code: "CNY",
    symbol: "¥",
    country: "cn-CN",
  },
  {
    currency_name: "Swedish Krona",
    currency_code: "SEK",
    symbol: "kr",
    country: "se-SE",
  },
  {
    currency_name: "New Zealand Dollar",
    currency_code: "NZD",
    symbol: "$",
    country: "nz-NZ",
  },
  {
    currency_name: "Mexican Peso",
    currency_code: "MXN",
    symbol: "$",
    country: "mx-MX",
  },
  {
    currency_name: "Singapore Dollar",
    currency_code: "SGD",
    symbol: "$",
    country: "sg-SG",
  },
  {
    currency_name: "Hong Kong Dollar",
    currency_code: "HKD",
    symbol: "$",
    country: "hk-HK",
  },
  {
    currency_name: "Norwegian Krone",
    currency_code: "NOK",
    symbol: "kr",
    country: "no-NO",
  },
  {
    currency_name: "South African Rand",
    currency_code: "ZAR",
    symbol: "R",
    country: "za-ZA",
  },
  {
    currency_name: "South Korean Won",
    currency_code: "KRW",
    symbol: "₩",
    country: "kr-KR",
  },
  {
    currency_name: "Turkish Lira",
    currency_code: "TRY",
    symbol: "₺",
    country: "tr-TR",
  },
  {
    currency_name: "Tunisian Dinars",
    currency_code: "TND",
    symbol: "TND",
    country: "tn-TN",
  },
  {
    currency_name: "Russian Ruble",
    currency_code: "RUB",
    symbol: "₽",
    country: "ru-RU",
  },
  {
    currency_name: "Brazilian Real",
    currency_code: "BRL",
    symbol: "$",
    country: "br-BR",
  },
  {
    currency_name: "Malaysian Ringgit",
    currency_code: "MYR",
    symbol: "RM",
    country: "my-MY",
  },
  {
    currency_name: "Thai Baht",
    currency_code: "THB",
    symbol: "฿",
    country: "th-TH",
  },
  {
    currency_name: "United Arab Emirates Dirham",
    currency_code: "AED",
    symbol: "AED",
    country: "ae-AE",
  },
  {
    currency_name: "Saudi Riyal",
    currency_code: "SAR",
    symbol: "SAR",
    country: "sa-SA",
  },
];
