export const currencies = [
  { currency_name: "US Dollar", currency_code: "USD", symbol: "$" },
  { currency_name: "Euro", currency_code: "EUR", symbol: "€" },
  { currency_name: "Japanese Yen", currency_code: "JPY", symbol: "¥" },
  { currency_name: "British Pound", currency_code: "GBP", symbol: "£" },
  { currency_name: "Indian Rupee", currency_code: "INR", symbol: "₹" },
  { currency_name: "Australian Dollar", currency_code: "AUD", symbol: "$" },
  { currency_name: "Canadian Dollar", currency_code: "CAD", symbol: "$" },
  { currency_name: "Swiss Franc", currency_code: "CHF", symbol: "CHF" },
  { currency_name: "Chinese Yuan", currency_code: "CNY", symbol: "¥" },
  { currency_name: "Swedish Krona", currency_code: "SEK", symbol: "kr" },
  { currency_name: "New Zealand Dollar", currency_code: "NZD", symbol: "$" },
  { currency_name: "Mexican Peso", currency_code: "MXN", symbol: "$" },
  { currency_name: "Singapore Dollar", currency_code: "SGD", symbol: "$" },
  { currency_name: "Hong Kong Dollar", currency_code: "HKD", symbol: "$" },
  { currency_name: "Norwegian Krone", currency_code: "NOK", symbol: "kr" },
  { currency_name: "South African Rand", currency_code: "ZAR", symbol: "R" },
  { currency_name: "South Korean Won", currency_code: "KRW", symbol: "₩" },
  { currency_name: "Turkish Lira", currency_code: "TRY", symbol: "₺" },
  { currency_name: "Tunisian Dinars", currency_code: "TND", symbol: "TND" },
  { currency_name: "Russian Ruble", currency_code: "RUB", symbol: "₽" },
  { currency_name: "Brazilian Real", currency_code: "BRL", symbol: "$" },
  { currency_name: "Malaysian Ringgit", currency_code: "MYR", symbol: "RM" },
  { currency_name: "Thai Baht", currency_code: "THB", symbol: "฿" },
  {
    currency_name: "United Arab Emirates Dirham",
    currency_code: "AED",
    symbol: "AED",
  },
  { currency_name: "Saudi Riyal", currency_code: "SAR", symbol: "SAR" },
];
